### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by ttriche** [splatlab/mantis#1]
tim@tim-ThinkPad-T470:~/Dropbox/mantis$ make NH=1  coloreddbg
```
g++ -std=c++11 -Wall   -Ofast  -m64 -I. -Isdsl/include -Wno-unused-result -Wno-strict-aliasing -Wno-unused-function -Wno-sign-compare  coloreddbg.cc -c -o coloreddbg.o
gcc -std=gnu11 -Wall   -Ofast  -m64 -I. -Wno-unused-result -Wno-strict-aliasing -Wno-unused-function -Wno-sign-compare -Wno-implicit-function-declaration  cqf/gqf.c -c -o cqf/gqf.o
g++ -std=c++11 -Wall   -Ofast  -m64 -I. -Isdsl/include -Wno-unused-result -Wno-strict-aliasing -Wno-unused-function -Wno-sign-compare  hashutil.cc -c -o hashutil.o
g++ -std=c++11 coloreddbg.o cqf/gqf.o hashutil.o   -Ofast -lsdsl -lpthread -lboost_system -lboost_thread -lm -lz -lrt -o coloreddbg
```

tim@tim-ThinkPad-T470:~/Dropbox/mantis$ ./coloreddbg raw/incqfs.lst raw/experiment_cutoffs.lst raw/ 
```
Reading CQF 0 Seed 2038074761
Sample id SRR191411 cut off 1
Reading CQF 1 Seed 2038074761
Sample id SRR191403 cut off 1
Sampling eq classes based on 67108864 kmers.
Segmentation fault (core dumped)
```

This doesn't seem like the desired behavior... ?

**Comment by rob-p** [comment]
Hi Tim,

  Thanks for reporting this.  Since this just made it out in the wild, we haven't had a chance to test it on anything apart from our own configuration yet, so your feedback is very useful.  The makefile currently makes some assumptions about the hardware (in terms of compile flags).  Could you please let us know what type of system you're running on?  Specifically, what is the model of the CPU?

Thanks!
Rob

**Comment by prashantpandey** [comment]
Hi Tim,

Indeed this is not the desired behavior. I just cloned the repo in a fresh location and executed the exact same commands as you mentioned and it worked perfectly for me. 

Could you please send what Rob asked and also the core dump to look into? 

Thanks,
Prashant

**Comment by prashantpandey** [comment]
Also, I see that you have compiled the code using `NH=1` flag. Just to confirm, that would mean you have an older than Haswell machine.

**Comment by ttriche** [comment]
re: CPU: 

tim@tim-ThinkPad-T470:~$ cat /proc/cpuinfo  | head -26
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 78
model name	: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
stepping	: 3
microcode	: 0xba
cpu MHz		: 2800.000
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		:
bogomips	: 5616.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

That said, I tried it with both NH=1 and without, and I get a core dump either way.  Let me see about grabbing both.

**Comment by ttriche** [comment]
OK, I dumped cores with and without NH=1.
It segfaults a little faster without NH=1 ;-)

[core.without_NH_equals_1.zip](https://github.com/splatlab/mantis/files/1464093/core.without_NH_equals_1.zip)
[core.with_NH_equals_1.zip](https://github.com/splatlab/mantis/files/1464094/core.with_NH_equals_1.zip)

**Comment by ttriche** [comment]
nb.  here is what I did to generate each:

With NH=1:
```
make clean 
ulimit -c unlimited
make NH=1 coloreddbg
./coloreddbg raw/incqfs.lst raw/experiment_cutoffs.lst raw/
```

Without:
```
make clean 
ulimit -c unlimited
make coloreddbg
./coloreddbg raw/incqfs.lst raw/experiment_cutoffs.lst raw/
```

**Comment by ttriche** [comment]
Duh, I'm an idiot, it would help if I pulled down all those SRA experiments...

tim@tim-ThinkPad-T470:~/Dropbox/mantis$ head raw/experiment_cutoffs.lst 
```
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925708 20
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925696 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925702 20
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925711 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925723 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925729 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925724 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925716 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925688 50
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925737 50
```
tim@tim-ThinkPad-T470:~/Dropbox/mantis$ ls /mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925737
```
ls: cannot access '/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR925/SRR925737': No such file or directory
```

**Comment by rob-p** [comment]
I see.  So we should definitely be checking for dike existence instead of segfaulting!  Also, the paths in the example are relative to our system.  We should have a script thay grabs test files and generates a cutoff list with the appropriate local paths.

**Comment by prashantpandey** [comment]
No, you don't need to pull these experiments. The code extracts the last part of the file path which is the accession. It then uses builds a map from accession to the cutoff. The exact file path is not looked up.

**Comment by prashantpandey** [comment]
Hi Tim,

How much RAM do you have on the machine where you are running this? You need at least 18GB to create the CQF data structure.

Also, I can't analyze the core dump because I don't have the same executable that was used to generate the code dump.
What you can do is:
```
ulimit -c unlimited
make D=1 coloreddbg
./coloreddbg raw/incqfs.lst raw/experiment_cutoffs.lst raw/
gdb coloreddbg core
```
And then on the gdb console:
```
backtrace
```
Could you send what you see there?

Thanks,
Prashant

**Comment by ttriche** [comment]
I have 32GB on this box but may be sitting on some of it, between Chrome
and R and Python.  Let me see what I can pull out of it.

Is it obvious from the cpuinfo whether the CPU is Haswell or later?  I
honestly don't keep track much any more.  I would pop this onto an HPC node
except USC's is down and mine in MI are not installed yet.  (D'oh)



--t

**Comment by ttriche** [comment]
```
Reading symbols from coloreddbg...done.
[New LWP 18298]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./coloreddbg raw/incqfs.lst raw/experiment_cutoffs.lst raw/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memset_avx2_erms ()
    at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
141	../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: No such file or directory.
(gdb) backtrace
#0  __memset_avx2_erms ()
    at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
#1  0x000055bf0c33a91d in ColoredDbg<SampleObject<CQF<KeyObject>*>, KeyObject>::construct(SampleObject<CQF<KeyObject>*>*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >&, std::unordered_map<BitVector, std::pair<unsigned long, unsigned long>, sdslhash<BitVector>, std::equal_to<BitVector>, std::allocator<std::pair<BitVector const, std::pair<unsigned long, unsigned long> > > >&, unsigned long) ()
#2  0x000055bf0c32fc3d in main ()
```

**Comment by prashantpandey** [comment]
Hi Tim,

I have just pushed a patch in which I am checking if the memory allocation for the CQF data structure is correct. Could you please check out the latest code and give it a try and let me know if you still see a segfault.

Thanks,
Prashant

**Comment by ttriche** [comment]
Looks like it's working:

```
tim@tim-ThinkPad-T470:~/Dropbox/mantis$ ./coloreddbg raw/incqfs.lst
raw/experiment_cutoffs.lst raw/
Reading CQF 0 Seed 2038074761
Sample id SRR191411 cut off 1
Reading CQF 1 Seed 2038074761
Sample id SRR191403 cut off 1
Sampling eq classes based on 67108864 kmers.
Constructing the colored dBG.
Final colored dBG has 518980 k-mers and 3 equivalence classes.
Serializing CQF and eq classes in raw/
```
...

--t

**Comment by prashantpandey** [comment]
It seems earlier when it gave a segfault you didn't have enough RAM available on the machine. 

Thanks,
Prashant

**Comment by ttriche** [comment]
I think you're right -- 

$ free  -h
```
              total        used        free      shared  buff/cache   available
Mem:            31G        8.3G        3.4G        795M         19G         21G
Swap:          2.0G        1.3G        735M
```

Sorry for the distraction.
