### ISSUE TITLE
"Can't allocate qf blocks" because key_bits is (apparently) wrong.

### ISSUE THREAD

**Issue by rsharris** [splatlab/mantis#10]
I'm trying to run mantis on a small test set, to work out bugs in my understanding before I try it on the usual ≈2600 experiment data set.  I'm trying to follow the example described in the mantis paper's methods, and what is shown in this repo's readme.  Full details of the steps I ran, below.

My example fails when I attempt to do mantis build.  The specific error message is generated by cqf/gqf.c:
   Can't allocate qf blocks: Cannot allocate memory
but some debugging/snooping reveals that the problem results from qf_init() begin passed nslots=2^34 and key_bits being smaller than 34.  I haven't been able to figure out why that has happened, where I have gone wrong.

Because key_bits < log2(nslots), the code ends up trying to allocate something close to 2^64 bytes.
While gqf.c contains an assert that would detect this error condition
  assert(key_remainder_bits > 0)
asserts are hardwired off in that module.

I note that if I do mantis build with the two example CQFs in the repo, it works.  In that case, it seems qf_init  is given key_bits=40.  This suggests (to me) that my problem came from how I built by CQFs, but it's not at all clear to me what I did wrong.

Apparently the call to qf_init() results from this line in colereddbg.cc
	ColoredDbg<SampleObject<CQF<KeyObject>*>, KeyObject> cdbg( ...
and that appears to be using key_bits that it derived from my CQF file.  One guess is that it relates to the number of slots in that file, and it does seem that when I try my CQFs, key_bits=8 plus the number of slots in the CQF.  But the example CQF files in the repo have file sizes that suggest 20 slots were used, yet somehow key_bits=40 for them.

FWIW I'm using squeakr and mantis source code pulled from the repos today.

What I ran:

My example consists of five small fastq files which should be publicly available at
   https://github.com/medvedevgroup/SbtPlayData

Following the description in the mantis paper's methods, I used ntcard to determine the number of slots for each CQF. This table shows the results from ntcard and the calculation of slots.

  #experiment F0    f1    f2   s     log2Slots slots  slots/s
  EXPERIMENT1 32384 18880 1535 57857 17        131072 2.265
  EXPERIMENT2 46400 27328 1087 83457 17        131072 1.571
  EXPERIMENT3 34048 18816 1343 63169 17        131072 2.075
  EXPERIMENT4 43712 24768 1279 80321 17        131072 1.632
  EXPERIMENT5 21120 11584 1023 39169 16        65536  1.673

So I created CQFs like this:

  squeakr_count -k 20 -s 17 -t 1 -g EXPERIMENT1.fastq.gz
  squeakr_count -k 20 -s 17 -t 1 -g EXPERIMENT2.fastq.gz
  squeakr_count -k 20 -s 17 -t 1 -g EXPERIMENT3.fastq.gz
  squeakr_count -k 20 -s 17 -t 1 -g EXPERIMENT4.fastq.gz
  squeakr_count -k 20 -s 16 -t 1 -g EXPERIMENT5.fastq.gz

And created file lists for mantis like this

  echo EXPERIMENT1.fastq.gz.ser >  incqfs.lst
  echo EXPERIMENT2.fastq.gz.ser >> incqfs.lst
  echo EXPERIMENT3.fastq.gz.ser >> incqfs.lst
  echo EXPERIMENT4.fastq.gz.ser >> incqfs.lst
  echo EXPERIMENT5.fastq.gz.ser >> incqfs.lst

  echo "EXPERIMENT1 1" >  experiment_cutoffs.lst
  echo "EXPERIMENT2 1" >> experiment_cutoffs.lst
  echo "EXPERIMENT3 1" >> experiment_cutoffs.lst
  echo "EXPERIMENT4 1" >> experiment_cutoffs.lst
  echo "EXPERIMENT5 1" >> experiment_cutoffs.lst

Then tried to run mantis like this (and got the error described above)

  mkdir cdbg
  mantis build -i incqfs.lst -c experiment_cutoffs.lst -o cdbg/

What am I doing wrong?

Thanks for any help,
Bob H

**Comment by rsharris** [comment]
After some additional snooping, I think the current version of squeaker isn't capable of producing CQFs with the same attributes as the ones in the mantis distribution.

Looking at the header of SRR191411_exact.ser (i.e. the first 128 bytes, which correspond to the quotient_filter_metadata struct), I find it has
  nslots = 2^19
  key_bits = 40
  bits_per_slot = 21
whereas if I do "squeakr_count -k 20 -s 20 -t 1 -g EXPERIMENT1.fastq.gz", I get a file with
  nslots = 2^20
  key_bits = 28
  bits_per_slot = 8

It appears that squeakr_count sets key_bits to qbits+8, where qbits is the value of the --log-slots setting.  After this is set (in qf_init) I don't find any place where it would be changed.  Similarly, after nslots is set, it doesn't look like it can change.

I don't see how the user can control any of this *other* than the --log-slots setting.

Of course I could be wrong about this; it's all reverse engineering.

Were the CQF example files created by something else?

P.S. Using "squeakr_count -s 20" to create my five CQFs does get my past the allocation error.  However, I get a segfault later (somewhere after "Reinitializing colored DBG after the sampling phase") that I haven't explored yet.

Note: My goal is to include mantis in a manuscript for another tool I'm working on for the same problem space.  I'd like to be able to provide timing comparisons, but at present I haven't figured out what is the right way to use it.

**Comment by prashantpandey** [comment]
@rsharris, I think you are using Squeakr-approximate to construct Squeakr files.
For Mantis, we currently, only support only Squeakr-exact (https://github.com/splatlab/squeakr/tree/exact).
If you use Squeakr-exact, the code sets the number of key bits to `2*K` and for K=20 key bits would be 40. This way Mantis can process Squeakr outputs.

PS: I am currently in the middle of releasing a new Squeakr API to merge all branches and other improvements. It should be up soon.

**Comment by rsharris** [comment]
Looks like that works.  I haven't yet checked that the results I get from mantis query are correct, but build and query run to completion with no noticeable problems.

I was held up for a while by the parsing problem in squeakr exact, which I've posted as a new issue over in that repo.

Thanks for getting me past this!

**Comment by prashantpandey** [comment]
Sure. No problem. And thanks for bringing up all these issues.
With this new Squeakr API (that I am working on), we will have only one branch and that will get rid of these issues.
