### ISSUE TITLE
humanRNA_40k bigger than expected

### ISSUE THREAD

**Issue by MitraDarja** [splatlab/mantis#23]
Hi, 

I am interested in using the 39,400 experiments you posted here (https://github.com/splatlab/mantis/blob/mergeMSTs/experiments/humanRNA_40k.accessions) and while not all data is downloaded yet (around 500 experiments are still missing), the gzipped fastq files take up already 56 TB of space, which is greater than the 2,33 TB you reprted in "An Incrementally Updatable and Scalable System for Large-Scale Sequence Search using LSM Trees". 

Do you have an idea where this difference in size could be coming from? 

Best Wishes, 
Mitra

**Comment by fataltes** [comment]
Dear @MitraDarja ,

Thank you for bringing up this issue to our attention.

You are absolutely correct and the mistake is on our side which will be edited in the last revision of the paper.

I reran the size calculation of all the files based on the same list uploaded on github and it is in fact 111TB.

Thank you,
Fatemeh

**Comment by MitraDarja** [comment]
Thanks for the fast reply. 
Is the size of 970 GB for the squeakr files correct? Did you use the same cutoffs as in the original Mantis paper for k=20 or did you adapt the number for k=23?

**Comment by fataltes** [comment]
Dear @MitraDarja ,

I also ran the same command to calculate size of squeakrs too.
That is also different from the paper and is 2.575TB.
Also corrected that in the paper too.

It seems that I have put the numbers some time before the full procedure ended and then forgot to update them.

Thanks to you the numbers will be correct for the final revision.

To answer your other question, yes. The cutoffs are the same as original Mantis for k=20 and for your convenience I have added the list of squeakr files to the github [here](https://github.com/splatlab/mantis/blob/mergeMSTs/experiments/humanRNA_40k.squeakrs) which contain the cutoff in their names that you can directly use.

Thanks again,
Fatemeh

**Comment by MitraDarja** [comment]
Thanks for the fast reply, I will then close the issue now. :)
