### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by RSherman15** [splatlab/mantis#3]
Hi, I'm currently getting a segfault when trying to run mantis on my own data. I can run on the sample data provided just fine. I definitely have enough memory allocated.

I get a segfault after printing that CQF 0 is being read, but before printing that the cutoff file was read, so I'm not sure if I'm creating the cutoff file wrong -- I'm not using samples with SRA accessions, so my cutoff file just has a paths to the fastqs used to generate the .ser files and the cutoffs (the path to one of the fastqs anyhow -- I input two fastqs per squeakr file, as it's paired end data. Squeakr named the .ser file after the first of the two, which is the path I then use for the cutoff file). What exactly should the cutoff file look like when it's not SRA data?

```
Reading CQF 0 Seed 2038074761
Segmentation fault
```

**Comment by prashantpandey** [comment]
Hi Rachel,

Could you share how your cutoff file looks like? 

Basically, the code expects the path in the cutoff file to have `<SRA_accession>` at the end. And the corresponding CQF file must be named as `<SRA_accession>_exact.ser`. 
Here, the common thing between the path in the cutoff file and input CQF file is the `SRA_accession`. But it doesn't have to be the SRA accession, it can be anything, but it has to be same.

```
For example:
Cutoff:
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR191/SRR191411 1 
/mnt/nfsbio/ftp.sra.ebi.ac.uk/vol1/fastq/SRR191/SRR191403 1 

Input CQFs file:
data/SRR191411_exact.ser                                                        
data/SRR191403_exact.ser 
```

Thanks,
Prashant

**Comment by prashantpandey** [comment]
And thanks for making us aware of these issues. 
We should also document this so that people in future don't see this issue.

Thanks,
Prashant

**Comment by RSherman15** [comment]
Ah, great, thanks. My issue was that my .ser files were not NAME_exact.ser.
My cutoff file was of the format:
```
SAMPLE_A 5
SAMPLE_B 5
```
...

for `SAMPLE_A.ser `and `SAMPLE_B.ser`

but I didn't realize I needed the `_exact ` in there (especially because these aren't exact since you don't seem to have an exact version of Squeakr released (unless I missed something in the Squeakr README?).

**Comment by prashantpandey** [comment]
Hi Rachel,

You are right. You would need Squeakr exact for this. I will release the code for Squeakr exact ASAP.

Thanks,
Prashant

**Comment by RSherman15** [comment]
Great! I assume I can still use mantis with the inexact CQFs though, the results will just have a non zero false positive rate, right?

**Comment by prashantpandey** [comment]
Yes.
